apiVersion: apps/v1
kind: Deployment
metadata:
  name: fake-post-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fake-post
  template:
    metadata:
     labels:
       app: fake-post
    spec:
      containers:
        - image: service/fake-post:latest
          imagePullPolicy: Never
          name: fake-post
          ports:
            - containerPort: 8081
          resources:
            limits:
              memory: 256Mi
            requests:
              cpu: 75m
              memory: 64Mi
