apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  type: LoadBalancer      # тип доступу до сервісу, ClusterIp - значення за замовчуванням і може бути пропущене
  ports:
    - port: 8080         # порт по якому можна звератись до сервісу
      targetPort: 8080 # порт контейнера
  selector:
    app: server      # селектор, всі Pod з даним селектором, будуть підключені до даного сервісу
